# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SuiteSparse::metis SuiteSparse::suitesparseconfig SuiteSparse::amd SuiteSparse::btf SuiteSparse::camd SuiteSparse::ccolamd SuiteSparse::colamd SuiteSparse::cholmod SuiteSparse::cxsparse SuiteSparse::klu SuiteSparse::ldl SuiteSparse::umfpack SuiteSparse::spqr)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target SuiteSparse::metis
add_library(SuiteSparse::metis STATIC IMPORTED)

# Create imported target SuiteSparse::suitesparseconfig
add_library(SuiteSparse::suitesparseconfig STATIC IMPORTED)

# Create imported target SuiteSparse::amd
add_library(SuiteSparse::amd STATIC IMPORTED)

set_target_properties(SuiteSparse::amd PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::btf
add_library(SuiteSparse::btf STATIC IMPORTED)

set_target_properties(SuiteSparse::btf PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::camd
add_library(SuiteSparse::camd STATIC IMPORTED)

set_target_properties(SuiteSparse::camd PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::ccolamd
add_library(SuiteSparse::ccolamd STATIC IMPORTED)

set_target_properties(SuiteSparse::ccolamd PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::colamd
add_library(SuiteSparse::colamd STATIC IMPORTED)

set_target_properties(SuiteSparse::colamd PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::cholmod
add_library(SuiteSparse::cholmod STATIC IMPORTED)

set_target_properties(SuiteSparse::cholmod PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::metis;SuiteSparse::amd;SuiteSparse::camd;SuiteSparse::colamd;SuiteSparse::ccolamd;SuiteSparse::suitesparseconfig;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework"
)

# Create imported target SuiteSparse::cxsparse
add_library(SuiteSparse::cxsparse STATIC IMPORTED)

set_target_properties(SuiteSparse::cxsparse PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::klu
add_library(SuiteSparse::klu STATIC IMPORTED)

set_target_properties(SuiteSparse::klu PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::amd;SuiteSparse::colamd;SuiteSparse::btf;SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::ldl
add_library(SuiteSparse::ldl STATIC IMPORTED)

set_target_properties(SuiteSparse::ldl PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::suitesparseconfig"
)

# Create imported target SuiteSparse::umfpack
add_library(SuiteSparse::umfpack STATIC IMPORTED)

set_target_properties(SuiteSparse::umfpack PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::amd;SuiteSparse::camd;SuiteSparse::colamd;SuiteSparse::ccolamd;SuiteSparse::cholmod;SuiteSparse::suitesparseconfig;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework"
)

# Create imported target SuiteSparse::spqr
add_library(SuiteSparse::spqr STATIC IMPORTED)

set_target_properties(SuiteSparse::spqr PROPERTIES
  INTERFACE_LINK_LIBRARIES "SuiteSparse::camd;SuiteSparse::ccolamd;SuiteSparse::cholmod;SuiteSparse::metis;SuiteSparse::suitesparseconfig;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework"
)

# Import target "SuiteSparse::metis" for configuration ""
set_property(TARGET SuiteSparse::metis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::metis PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "m"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libmetis.a"
  )

# Import target "SuiteSparse::suitesparseconfig" for configuration ""
set_property(TARGET SuiteSparse::suitesparseconfig APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::suitesparseconfig PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libsuitesparseconfig.a"
  )

# Import target "SuiteSparse::amd" for configuration ""
set_property(TARGET SuiteSparse::amd APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::amd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libamd.a"
  )

# Import target "SuiteSparse::btf" for configuration ""
set_property(TARGET SuiteSparse::btf APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::btf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libbtf.a"
  )

# Import target "SuiteSparse::camd" for configuration ""
set_property(TARGET SuiteSparse::camd APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::camd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libcamd.a"
  )

# Import target "SuiteSparse::ccolamd" for configuration ""
set_property(TARGET SuiteSparse::ccolamd APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::ccolamd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libccolamd.a"
  )

# Import target "SuiteSparse::colamd" for configuration ""
set_property(TARGET SuiteSparse::colamd APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::colamd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libcolamd.a"
  )

# Import target "SuiteSparse::cholmod" for configuration ""
set_property(TARGET SuiteSparse::cholmod APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::cholmod PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libcholmod.a"
  )

# Import target "SuiteSparse::cxsparse" for configuration ""
set_property(TARGET SuiteSparse::cxsparse APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::cxsparse PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libcxsparse.a"
  )

# Import target "SuiteSparse::klu" for configuration ""
set_property(TARGET SuiteSparse::klu APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::klu PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libklu.a"
  )

# Import target "SuiteSparse::ldl" for configuration ""
set_property(TARGET SuiteSparse::ldl APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::ldl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libldl.a"
  )

# Import target "SuiteSparse::umfpack" for configuration ""
set_property(TARGET SuiteSparse::umfpack APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::umfpack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libumfpack.a"
  )

# Import target "SuiteSparse::spqr" for configuration ""
set_property(TARGET SuiteSparse::spqr APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(SuiteSparse::spqr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/Users/hengsun/Documents/Thesis/suitesparse-metis-for-windows-1.4.0/lib/libspqr.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
